server:
  port: 8567
spring:
  datasource:
    url: jdbc:mysql://medikey-mysql.cilhfacxickg.ap-south-1.rds.amazonaws.com:3306/medikey
    username: admin
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB  # Set maximum file size
      max-request-size: 15MB  # Set maximum request size
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: medikey.health@gmail.com
    password: endwzwjzpkqpqhrx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true